#                                                                        #
# Default subroutes configuration for the Neos.Seo package               #
#                                                                        #

##
# XML Sitemap

-
  name:  'XML Sitemap'
  uriPattern: '{node}<xmlSitemapPath>'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'xml.sitemap'
  routeParts:
    'node':
      handler:     'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: TRUE
  appendExceedingArguments: TRUE
