Neos:
  Neos:
    typoScript:
      autoInclude:
        'Neos.Seo': TRUE

    userInterface:
      translation:
        autoInclude:
          'Neos.Seo': ['NodeTypes/*']

  Seo:
    # Twitter Card settings
    twitterCard:
      # the Twitter handle for the twitter:site attribution
      siteHandle: ~
