Neos:
  Seo:
    # robots.txt settings
    robotsTxt:
      dimensionsPresets: null
    # Twitter Card settings
    twitterCard:
      # the Twitter handle for the twitter:site attribution
      siteHandle: ~
    # Facebook settings
    facebook:
      # List of facebook user ids of your pages/apps administrators
      admins: []
    # Social profile for the structured data object
    socialProfile:
      # `type` can be either `Person` or `Organization`
      type: Person
      # `logo` can be for example `resource://Vendor.Site/Public/Images/MyLogo.png`
      logo: ''
      profiles:
        twitter: ~
        facebook: ~
        instagram: ~
        linkedIn: ~
        youTube: ~

